# Generated by Django 5.1.4 on 2025-06-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer')], max_length=20, null=True),
        ),
    ]
